version = "1.0"

[main]
name.en = "MS fonts"
name.fr = "MS fonts"

    [main.msfonts]

    [main.msfonts.msfonts_enabled]
    ask.en = "Would you like to add the ©Microsoft fonts for Collabora ?"
    ask.fr = "Souhaitez-vous ajouter les polices de ©Microsoft pour Collabora ?"
    type = "boolean"
    yes = "true"
    no = "false"
