version = "1.0"

[main]
name.en = "MS fonts"
name.fr = "MS fonts"

    [main.msfonts]

    [main.msfonts.msfonts_enabled]
    ask.en = "Would you like to add the non-free Microsoft® fonts for Collabora?"
    ask.fr = "Souhaitez-vous ajouter les polices non-libres de Microsoft® pour Collabora ?"
    type = "boolean"
    yes = "true"
    no = "false"
[main.add_domains.nextcloud_domain]
ask.fr = "Domaine nextcloud actuel"
ask.en = "Current nextcloud domain"
default = ""
type = "string"
bind = "null"

[main.add_domains]
name.en = "Extra domains"
name.fr = "Domaines supplémentaires"

[main.add_domains.extra_domain_1]
ask.fr = "Premier domaine supplémentaire"
ask.en = "First extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "null"

[main.add_domains.extra_domain_2]
ask.fr = "Deuxième domaine supplémentaire"
ask.en = "Second extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "null"

[main.add_domains.extra_domain_3]
ask.fr = "Troisième domaine supplémentaire"
ask.en = "Third extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "null"

[main.add_domains.extra_domain_4]
ask.fr = "Quatrième domaine supplémentaire"
ask.en = "Fourth extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "null"
