#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "coolwsd" >/dev/null; then
    yunohost service remove "coolwsd"
fi
ynh_config_remove_systemd --service="coolwsd"

ynh_config_remove_nginx

ynh_safe_rm "/etc/coolwsd"

# FIXME: is it still required?
# Fix "rm: cannot remove '/etc/apt/apt.conf.d/25loolwsd': No such file or directory"
# on apt remove
touch /etc/apt/apt.conf.d/25loolwsd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
