#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# needed if oldest version
ynh_app_setting_set --key=protect_against_basic_auth_spoofing --value="false"

#=================================================
# REMOVE OLD SERVICE INTEGRATION IN YUNOHOST
#=================================================

if ynh_hide_warnings yunohost service status "loolwsd" >/dev/null; then
    ynh_script_progression "Removing loolwsd service integration..."
    yunohost service remove "loolwsd"
fi

# Remove the legacy systemd config
ynh_config_remove_systemd --service="loolwsd"

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="coolwsd" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_config_add --template="root_index.html" --destination="$install_dir/index.html"

chmod 640 "$install_dir/index.html"
chown -R "$app:www-data" "$install_dir"

#=================================================
# UPGRADE CONFIG
#=================================================
ynh_script_progression "Upgrading config file..."

ynh_config_add --template="coolwsd.xml" --destination="/etc/coolwsd/coolwsd.xml"

chown cool: "/etc/coolwsd/coolwsd.xml"
chmod 640 "/etc/coolwsd/coolwsd.xml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

yunohost service add "coolwsd" --description="Collabora online office suite" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="coolwsd" --action="restart" --log_path="systemd" --wait_until="Ready to accept connections"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
